image: alpine

stages:
    - schematicPDF

scheamticPDF:
    stage: schematicPDF
    before_script:
        apk update
    script:
        mkdir out/
        python3 -m kicad-automation-scripts.src.eeschema.schematic export -f pdf --all_pages --default_directory SensorExtentionBoard/SensorExtentionBoard.sch out/
        ssh deployuser@elon.sdsurocketproject.org "rm -f /var/www/html/wikistatic/Helix-Test-Rig-Hardware/SensorExtentionBoard.pdf"
        scp SensorExtentionBoard/SensorExtentionBoard.pdf deployuser@elon.sdsurocketproject.org:/var/www/html/wikistatic/Helix-Test-Rig-Hardware/
    only:
        - master